### PR TITLE
Fix monopoly taking resources

### LINKED ISSUE #23: Can always Monopoly
Can always press monopoly even if you don't have one

### PR DESCRIPTION
**Pull request by garcia42**
fixes #23

### CODE REVIEW

File: catan-server-module/catan-server.js [hunk 1]
```diff
@@ -745,18 +745,18 @@ exports.handleNameChangeAttempts = function (io, socket, previousName, name, uui
...
   var resourceName = order[monopolyData.resource]
   var uuid = monopolyData.uuid
-  console.log('monopoly', resourceName, uuid)
-  var totalCards = 0
-  roomData[currentRoom].forEach(function (player) {
-    if (playerData[uuid].getPlayerIndex() !== player.getPlayerIndex()) {
-      totalCards += player.getCards().monopolyResource(monopolyData.resource)
-    }
-  })
   if (playerData[uuid].getCards().getResourceAmount(8) > 0) { // Can't use if have 0
```
Comment (marwahaha) [inline catan-server-module/catan-server.js]: One option is to use a "failfast approach", i.e. 

```
  if (playerData[uuid].getCards().getResourceAmount(8) === 0) {
 // Can't use if have 0
return;
}
...
```

Comment (garcia42) [reply catan-server-module/catan-server.js]: I prefer when a method hits the end of the method body to failing fast
